---
title: "Battle plan for JD+ related Tools"
format: pdf
format: html 
---


## This file 

### Objectives 

- define products and steps unambiguously

- highlight what has to be done for up coming presentations (Stace, Tsaug meetings...)

see it again..

### Scope 

All JD+ related tools : GUI and R packages 

R packages 

- dvlpt 

- tests

- doc (functions, readme)

GUI 

- test new features (HF,...)
- improve online documentation 

## Now page

Currently working on (details in TOPICS..)

### Maj doc refresh 

clarified txt and examples in 
- x13 regarima refresh 
- tramos eats 

Harmonize refresh policies names

#### refesh rjd3workspace 

special title in github page : ok 
rename domain spec to ref spec 

get set 
read sai: args + example : ok 






function toolkit .jdomain ?

get_active_specification(jsai) ?

fatih code 

#### Spotted x13 issues

- free parameters doesn't reestimate arima coeffs : true ?
- free parameters inst the default

# comportement avec la partie reg arim
## - n'efface pas set transform avec complete !! ISSUE ? voir GUI

# comportement avec partie x11
    ## DOC correction de x11 spec
    ## DOC correction de set_x11

## avec complete effacement de tous les params

# comportement avec partie benchmarking

    ## Doc correction set_benchmarking

#### Tests with ramps user def regressors 

#### T: Harmonize refresh names (with GUI)

#### Induced maj quarto book

#### Spotted tramoseats issues

- idem as x13 for refresh ?

- lack print elements in seats ? bcasts, forecasts ?



### rjd3prodcution 

What is indispensable for DT publi ?

- readme 

- functions names referenced 

= > ok, see the rest post publi 


To "solve":

- pb limitation insee regressors 

- why using "working day regressors" ?

- reformulation sur to each series (s-item) rather than seasonal adjustment model 

- assign 
    - pb examples ?

- compare 
    - Extract all series from a SA-Item : pb as not in the sa item .....
    
    

- data with holes ?

- modify_specification 

update here: Typical use case: after "estimation with user pre-specified outliers" (not automatic), outliers with
weak statistical significance (e.g. `p > 0.3`) are dropped to
simplify the regression specification.

là encore pb emploi "seasonal adjustment models" with "SAI"

- Set span minimum to a value: to see...

- title:  Variables named in workspace ? reviewed 

- pb of using experssion "regression outliers"

-  - `retrieve_outliers()` returns a named list where each element
   corresponds to a series in the workspace and contains the names
   of existing (detected or pre-specified) outliers.
 
- why this description
These functions allow extracting, exporting, and importing the
*calendrier jours ouvrés* (TD) regressors used in JDemetra+ workspaces

- select file 

why this title : "Diagnostics and Regression Selection for X13 Models" 

- pb use airpassengers, take an exmaple in a toolkit data base


Calendar regressors selection for X13 Models: new title 

LOOK : at isues ...



### CRAN

T: rjd3workspace, rjd3production

### Git issues


### Vignettes

T : rjd3production 

A: toolkit by topic

### Output doc 

- verif rjd3x13 output names, java dico 
link to java dico ?
pb = mise en forme (check first)

- idem tramoseats
- str d'un modele complet print and document : cf doc book : output descprition chap 


#### JD+ et packages 

Issues / Dvlpter meeting 

#### Nettoyage N: done ?

"N:/L120/SECTION MTS/JD_Installation_configuration"

simple fichier de texte avec des liens ?

"N:/L120/SECTION MTS/Admin_Section"

mettre à jour calendrier concours 

deplacer fichiier envt de travail dans 
"N:/L120/SECTION MTS/JD_Installation_configuration" (?)




#### Tests

(share with user group)

- mode (verifier formules)

- seasonal filters and seasonal sigma (anna: bilan)

- all calendar option 


#### New features (test and doc)


MAIN GUI + R
(Anna)
-	Pré-identification des gros outliers avant la sélection log/level (impact limité)
(rjdx13 and tramo seats...)

-	Intégration du pré-ajustement LP dans Tramo (comparable au X13) ? Not clear...(in GUI as well)

-	Sélection automatique des variables de jours ouvrables (amélioration dans Tramo et nouveauté dans X13, solution identique dans les deux algorithmes)

(tramo and or x13 ?)

- change "airline" display when printing a spec 


#### JD Cruncher 

- adaptation to tramo (first in v2)= if tramo remove (!!) all the x11 specific tests

- adaptation to v3

- parametrage poids indicateurs: up date doc + example! done ??

- ajouter valeurs coefficients et p-values (pour selection cjo) 

aujourd'hui: ajout params dans options d'output, lecture ad hoc de demetra_m.csv
but lire direct avec JDCruncheR (to do 1h)

- test validité chemin avant de cruncher (to do 1h)

- habillage output sans excel 

#### rjd3x13

- change "airline" display when printing a spec 

bias correction : non existing ? see technical doc

#### rjd3tramoseats 

- change "airline" display when printing a spec 

(look into Java: Tanguy)
- bias correction ?


#### rjd3workspace

cf issues fonctions à point et nommages


#### rjdqa en V3 ?

Alain started rjd3report 

#### rjd3toolkit 

Issue:

- remove holiday param (leave and change doc)

DOC

- trigonometric regressors

- sarima estimation

- UC arima decomposition (see Ine) (lack of info)

#### rjd3highfreq 

#### rjd3stl 


#### rjd3bench

#### rjd3sts 

#### rjd3revisions

### R packages V2

#### RJDemetra 

add : print model span 


#### rjdqa 

REVIEW

- resuscitate ? reparametrer ?

alain : tableau supplementaitre



                                                                                                                                 







