---
title: "T-rjd3x13 Mode Biais Sigma vector"
format: html
---

```{r}
#| label: loading-rjdverse
#| echo: true
#| eval: true
library("rjd3toolkit")
library("rjd3tramoseats")
```


## Issue 1: biais doc

- be able to explain formulas (WB stuff)

- mail karsten on formulas 

- test and issue ? on bais always corrected even if FLSA

- redo GUI : read WS and assess correction (rjd3workspace ? see needed adaptation in rjd3production)

### Code R JP souche

```{r}

#' Title
#'
#' @param y (linearized) Numerics. original series, perhaps corrected for deterministic effects. In that case it's exp(linearized). 
#' @param lt Numerics. trend of log(y)
#' @param ls Numerics. seasonal or periodic component of log(y)
#' @param li Numerics. irregular component of log(y)
#' @param period Numerics. Length of a cycle (of the periodic component)
#'
#' @return A data.frame with y, t, s, i, so that y=t*s*i
#' @details Based on the bias correction in SEATS. 
#' @examples
biasCorrection<-function(y, lt, ls, li, period){
  # TO DO. Check possible numerical problems in the canonical decomposition (ly != lt+ls+li) and throw a warning if differences are inacceptable
  t<-exp(lt)
  s<-exp(ls)
  i<-exp(li)
  n<-length(y)
  # rounding for non integer periods
  nc<-round(length(y)-n%%period)
  sbias<-mean(s[1:nc]) # sur l'ensemble de la periode (années completes) et pas année par année 
  s<-s/sbias
  ibias<-mean(i)
  t<-t*(ibias*sbias)
  # we correct some numerical problems that way (as in SEATS)
  sa<-y/s
  i<-sa/t
  
  return(data.frame(y=y, sa=sa, t=t, s=s, i=i))
}

## Test on tramo-seats SA data : is bias corrected 

```


### test rjd3tramoseats 


#### bais by default
```{r}

library("rjd3tramoseats")

# chgt de bais

# decocher bais

y <- rjd3toolkit::ABS$X0.2.09.10.M
s1<-rjd3tramoseats::tramoseats_spec("rsafull")
s2<-set_transform(
  s1,"Log")
# recup les comps en log 
summary(tramoseats_dictionary())
View(tramoseats_full_dictionary())

# Extract names of output of interest
user_defined_output <- tramoseats_dictionary()[tramoseats_dictionary() %in% c("y","ylin","s","t","i","decomposition.y_lin", 
"decomposition.sa_lin",
 "decomposition.t_lin",
 "decomposition.s_lin",
 "decomposition.i_lin",
 "decomposition.y_cmp",
 "decomposition.sa_cmp",
 "decomposition.t_cmp",
 "decomposition.s_cmp",
 "decomposition.i_cmp")]

user_defined_output

# Generate the corresponding output in an estimation
y <- rjd3toolkit::ABS$X0.2.09.10.M
m <- tramoseats(y, "rsafull", s2, userdefined=user_defined_output)
tail(m$user_defined)
# finaux en niveau 
 y<- m$user_defined$y
 s<- m$user_defined$s
 t<- m$user_defined$t
 i<- m$user_defined$i
ylin<- m$user_defined$ylin # doublon ? y lin en niveau 
# decomp serie linearisée en log
decomposition.y_lin<- m$user_defined$decomposition.y_lin # en log
decomposition.sa_lin<- m$user_defined$decomposition.sa_lin
decomposition.t_lin<- m$user_defined$decomposition.t_lin
decomposition.i_lin<- m$user_defined$decomposition.i_lin
# remise decomposition en niveau 
decomposition.y_cmp<- m$user_defined$decomposition.y_cmp  #y lin en niveau ? doublon 
decomposition.sa_cmp<- m$user_defined$decomposition.sa_cmp
decomposition.t_cmp<- m$user_defined$decomposition.t_cmp
decomposition.s_cmp<- m$user_defined$decomposition.s_cmp
decomposition.i_cmp<- m$user_defined$decomposition.i_cmp  

# visualiser, comparer, identifier: valider appellation

# verif egalites log vs niveau 
## y lin 
li<-round(decomposition.y_lin-log(ylin),6)
li
all.equal(decomposition.y_lin,log(ylin))
li2<-round(ylin-decomposition.y_cmp,6)
li2
all.equal(ylin,decomposition.y_cmp)
# la decomposition est faite en log et remise en niveau 
# sa : là on devrait voir si correction biais 
sa_d <-round(exp(decomposition.sa_lin)-decomposition.sa_cmp,6)
sa_d
# biais

# t : là on devrait voir si correction biais (remise)
t_d <-round(exp(decomposition.t_lin)-decomposition.t_cmp,6)
t_d

# s : là on devrait voir si correction biais moyenne à 1 ?
s_d <-round(exp(decomposition.t_lin)-decomposition.t_cmp,6)
t_d
# biais
 
## verif realloc components (doc)

```


#### bais FALSE

```{r}

library("rjd3tramoseats")

# chgt de bais

# decocher bais

y <- rjd3toolkit::ABS$X0.2.09.10.M
s1<-rjd3tramoseats::tramoseats_spec("rsafull")
s2<-set_transform(
  s1,"Log")
# recup les comps en log 
summary(tramoseats_dictionary())
View(tramoseats_full_dictionary())

# Extract names of output of interest
user_defined_output <- tramoseats_dictionary()[tramoseats_dictionary() %in% c("y","ylin","s","t","i","decomposition.y_lin", 
"decomposition.sa_lin",
 "decomposition.t_lin",
 "decomposition.s_lin",
 "decomposition.i_lin",
 "decomposition.y_cmp",
 "decomposition.sa_cmp",
 "decomposition.t_cmp",
 "decomposition.s_cmp",
 "decomposition.i_cmp")]

user_defined_output

# Generate the corresponding output in an estimation
y <- rjd3toolkit::ABS$X0.2.09.10.M
m <- tramoseats(y, "rsafull", s2, userdefined=user_defined_output)
tail(m$user_defined)
# finaux en niveau 
 y<- m$user_defined$y
 s<- m$user_defined$s
 t<- m$user_defined$t
 i<- m$user_defined$i
ylin<- m$user_defined$ylin # doublon ? y lin en niveau 
# decomp serie linearisée en log
decomposition.y_lin<- m$user_defined$decomposition.y_lin # en log
decomposition.sa_lin<- m$user_defined$decomposition.sa_lin
decomposition.t_lin<- m$user_defined$decomposition.t_lin
decomposition.i_lin<- m$user_defined$decomposition.i_lin
# remise decomposition en niveau 
decomposition.y_cmp<- m$user_defined$decomposition.y_cmp  #y lin en niveau ? doublon 
decomposition.sa_cmp<- m$user_defined$decomposition.sa_cmp
decomposition.t_cmp<- m$user_defined$decomposition.t_cmp
decomposition.s_cmp<- m$user_defined$decomposition.s_cmp
decomposition.i_cmp<- m$user_defined$decomposition.i_cmp  

# visualiser, comparer, identifier: valider appellation

# verif egalites log vs niveau 
## y lin 
li<-round(decomposition.y_lin-log(ylin),6)
li
all.equal(decomposition.y_lin,log(ylin))
li2<-round(ylin-decomposition.y_cmp,6)
li2
all.equal(ylin,decomposition.y_cmp)
# la decomposition est faite en log et remise en niveau 
# sa : là on devrait voir si correction biais 
sa_d <-round(exp(decomposition.sa_lin)-decomposition.sa_cmp,6)
sa_d
# biais

# t : là on devrait voir si correction biais (remise)
t_d <-round(exp(decomposition.t_lin)-decomposition.t_cmp,6)
t_d

# s : là on devrait voir si correction biais moyenne à 1 ?
s_d <-round(exp(decomposition.t_lin)-decomposition.t_cmp,6)
t_d
# biais
 
## verif realloc components (doc)

```



